#!/bin/bash

# TODO
# we need
# AWS_PROFILE
# AWS_DEFAULT_REGION
# AWS_DOMAIN
# AWS_DOMAIN_OWNER
# path to .aws
# path to .gradle gradle.properties

if [ -z "$1" ]; then
    echo "No AWS profile was given. Try 'aws-su titles-nonprod'"
    echo "Unsetting AWS_PROFILE"
    unset AWS_PROFILE
    exit 1
fi

echo "Logging into '$1'"
docker run --rm -it -v /path/to/.aws:/root/.aws sportradar/aws-azure-login --profile $1
export AWS_DEFAULT_REGION=ap-southeast-2
export AWS_PROFILE=$1

echo "default region $AWS_DEFAULT_REGION"
echo "profile $AWS_PROFILE"
echo "Getting codeartifact auth token..."
CODEARTY=`aws codeartifact get-authorization-token --domain $AWS_DOMAIN --domain-owner $AWS_DOMAIN_OWNER --query authorizationToken --output text --profile $AWS_PROFILE --region $AWS_DEFAULT_REGION`

if [[ "$CODEARTY" ]]; then
    sed -i '/^CODEARTIFACT_AUTH_TOKEN=/d' /path/to/.gradle/gradle.properties
    echo CODEARTIFACT_AUTH_TOKEN=$CODEARTY >> /path/to/.gradle/gradle.properties
    export CODEARTIFACT_AUTH_TOKEN=$CODEARTY
    echo "Done"
else
    echo "Failed to get codeartifact auth token"
    exit 1
fi
